### ISSUE TITLE
When entering bank teller, try putting an incorrect answer.

### ISSUE THREAD

**Issue by ghost** [lilhumza/Bank#14]
It just skips the auth

**Comment by alk0rani** [comment]
It does, lemme try fixing it.

**Comment by alk0rani** [comment]
Should work, try it and pelase let me know. @Draftyshark

**Comment by ghost** [comment]
still broken

**Comment by alk0rani** [comment]
How about now?

**Comment by ghost** [comment]
Answer 1 incorrectly and then do them correctly. It asks the questions a second time

**Comment by alk0rani** [comment]
I spent so long trying to figure it out just to realize I was calling it again by accident in BankTeller, lmao. Now it works.

**Comment by ghost** [comment]
umm you messed up my while loops in main

**Comment by ghost** [comment]
also cant access account info anymore. Have to do the loop twice to access it

**Comment by alk0rani** [comment]
Oh shoot did I? My bad, how does it mess it up? Also, account info still works for me?

**Comment by ghost** [comment]
Exiting bank teller returns to the main menu. Instead of bank

**Comment by ghost** [comment]
Also when you signIn
answer 1 question wrong
and then try to do them correctly, says its wrong

**Comment by ghost** [comment]
We should just remove the security questions... too many logic errors

**Comment by alk0rani** [comment]
Removing it would take more time, fixed the while loop problem. Let me check out the sign in problem.

**Comment by Draftyshark** [comment]
same problem

**Comment by alk0rani** [comment]
Doesn't go to the main menu for me? Also, I think it says that all the questions are wrong whenever you sign in because the information isn't saving. As opposed to when you make a new account and then sign in with it later (since the values are stored in an arrayList and I'm pretty sure I'm not reading it from a file). Anyway, I think we just need to read it from the file the values and add it to the arrayList when the user logs in and that should solve the problem. 

If this is too much of a hassle, we can remove the security questions if you want but I don't think it's worth it honestly.

**Comment by ghost** [comment]
Aight, try and fix it. If you can fix all the bugs, we'll keep it

**Comment by alk0rani** [comment]
It should work, hopefully. @Draftyshark Try it and let me know if there are any bugs.

**Comment by alk0rani** [comment]
Also is FileEncryption still working? @Draftyshark

**Comment by ghost** [comment]
As long as you LogOut via termial, yes FileEncryption works

**Comment by alk0rani** [comment]
Nice. Also I'm gonna be gone for about an hour just so you know. I'll be back soon.

**Comment by ghost** [comment]
qwd
qwe
315042
1234
212881.0
a a a 
a a a  +213213.0

Happens to file when you try to deposit something
security questions are being added to transactionHistory

**Comment by alk0rani** [comment]
I'm back. @Draftyshark I think it's fixed. If it isn't I'm gonna die. But anyways, if there are more problems about this I'll work on them at lunch tomorrow and then if they aren't fixed by then, we can remove everything that wasn't working.

**Comment by ghost** [comment]
yikes, the error still exists

dsf
dsa
664279
1234
-123039.0
a a a 
a a a  -21.0

btw, our code isnt very "new feature" freindly. Im gonna reevaluate the code on monday

**Comment by alk0rani** [comment]
it literally isn't doing that for me okay WHAT
i give up on life tbh

**Comment by alk0rani** [comment]
oh wait it is after you do the security questions thing, okay I'll fix that (hopefully)

**Comment by alk0rani** [comment]
@Draftyshark please, please tell me it works.

**Comment by ghost** [comment]
nope

**Comment by alk0rani** [comment]
YOU'RE KIDDING

**Comment by ghost** [comment]
[thinking](https://external-preview.redd.it/voMzrZYUq9_gW7-cx9mAsFpMI-uabTcEyaUNJUneXYk.gif?format=mp4&s=23e908927230977b40ff1670f037d93ff7bea567)

**Comment by alk0rani** [comment]
Alright try it, it definitely works on mine so I'm confused lmao.

**Comment by ghost** [comment]
Account.java has the bankteller file

**Comment by alk0rani** [comment]
lemme reupload my b

**Comment by ghost** [comment]
is bankteller gonna be the same?

**Comment by alk0rani** [comment]
yea

**Comment by ghost** [comment]
When it changes a specific transaction history it deletes all of them instead

**Comment by alk0rani** [comment]
ill fix that at lunch because i dont want to fail my data management test tmrw

**Comment by alk0rani** [comment]
otherwise everything works though right?

**Comment by ghost** [comment]
afaik yes

**Comment by alk0rani** [comment]
alright, i'll fix that and tomorrow will be organizing the code, documentation, and all of that stuff before we submit
